name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  turbostreamer:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        encoder: [oj, wankel]
        gemfile:
          - gemfiles/rails_6_0.gemfile
          - gemfiles/rails_6_1.gemfile
          - gemfiles/rails_7_0.gemfile
          - gemfiles/rails_7_1.gemfile
        allow_failures:
          - false
        include:
          - ruby: ruby-head
            gemfile: gemfiles/rails_7_1.gemfile
            encoder: oj
            allow_failures: true
          - ruby: ruby-head
            gemfile: gemfiles/rails_7_1.gemfile
            encoder: wankel
            allow_failures: true
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      ALLOW_FAILURES: "${{ matrix.allow_failures }}"

    steps:
      - name: Install YAJL
        run: |
          wget 'https://github.com/lloyd/yajl/archive/refs/tags/2.1.0.tar.gz'
          tar -xvf '2.1.0.tar.gz'
          cd 'yajl-2.1.0' && ./configure && make && sudo make install
          sudo ldconfig

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test:${{ matrix.encoder }} || $ALLOW_FAILURES
