name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  turbostreamer:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.2'
          - '3.3'
          - '3.4'
          - '3.5.0-preview1'
        rails-version:
          - 7.1
          - 7.2
          - 8.0
        encoder:
          - oj
          - wankel

    steps:
      - name: Install YAJL
        run: |
          wget 'https://github.com/lloyd/yajl/archive/refs/tags/2.1.0.tar.gz'
          tar -xvf '2.1.0.tar.gz'
          cd 'yajl-2.1.0' && ./configure && make && sudo make install
          sudo ldconfig

      - uses: actions/checkout@v4

      - run: |
          echo ""  >> Gemfile
          echo 'gem "rails", "${{ matrix.rails-version }}"' >> Gemfile

      - name: Add logger for Ruby 3.5 (no longer bundled gem, drop when rails adds)
        run: |
          echo ""  >> Gemfile
          echo 'gem "logger"' >> Gemfile
          echo ""  >> Gemfile
          echo 'gem "benchmark"' >> Gemfile

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test:${{ matrix.encoder }}
